import streamlit as st
import pandas as pd
import plotly.express as px
import re
import io

st.set_page_config(page_title="Log Analyzer", layout="wide")

st.title("📊 Server Log Analyzer")
st.write("Upload your Nginx/Apache log file to get started.")

# File uploader
uploaded_file = st.file_uploader("Choose a log file", type="txt")

if uploaded_file is not None:
    # Read file
    stringio = io.StringIO(uploaded_file.getvalue().decode("utf-8"))
    lines = stringio.readlines()

    # Parsing logic
    log_pattern = r'(?P<ip>\S+) - - \[(?P<timestamp>.*?)\] "(?P<request>.*?)" (?P<status>\d+) (?P<size>\S+) "(?P<referrer>.*?)" "(?P<user_agent>.*?)"'
    
    data = []
    for line in lines:
        match = re.search(log_pattern, line)
        if match:
            data.append(match.groupdict())

    df = pd.DataFrame(data)
    
    # Cleaning
    df['timestamp'] = pd.to_datetime(df['timestamp'].str.split(' ').str[0], format='%d/%b/%Y:%H:%M:%S', errors='coerce')
    df['status'] = pd.to_numeric(df['status'])
    df['size'] = pd.to_numeric(df['size'].replace('-', '0'))
    df['url'] = df['request'].str.split(' ').str[1]

    st.success(f"Parsed {len(df)} lines successfully!")

    # Layout for charts
    col1, col2 = st.columns(2)

    with col1:
        fig1 = px.pie(df, names='status', title="Response Status Codes")
        # Use 'width' instead of 'use_container_width' to stop warnings
        st.plotly_chart(fig1, width='stretch')

    with col2:
        # FIX 1: Use lowercase 'h' for Pandas 3.0+
        df_time = df.set_index('timestamp').resample('h').size().reset_index(name='requests')
        fig2 = px.line(df_time, x='timestamp', y='requests', title="Requests per Hour")
        st.plotly_chart(fig2, width='stretch')

    # Top URLs
    # FIX 2: Use the exact column names generated by reset_index() ('url' and 'count')
    top_urls = df['url'].value_counts().head(10).reset_index()
    top_urls.columns = ['url', 'count'] 
    
    st.write("### Top 10 Requested URLs")
    # FIX 3: Set index to 'url' (lowercase)
    st.bar_chart(top_urls.set_index('url'))

    # Data view
    st.write("### Raw Data")
    st.dataframe(df)
