# -*- coding: utf-8 -*-
"""log_opener.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZu11t1ahkmidJdFszFNmcCQrgNEixyS

# Log File Opener
Base guideline from SEJ: https://www.searchenginejournal.com/python-analysis-server-log-files/412898/
"""

import pandas as pd
import re
import glob

#Let's define a variable to match only GBot in logs.
bot = 'Googlebot|bingbot'

#Open log files and match only Gbot and bingbot.
log = glob.glob('*.log')

new_file = open('log_googlebot.csv',w,)

for single_log in log:
 with open(single_log, 'r') as file:
  for line in file:
   if re.search(bot, line):
    new_file.write(line)